name: KTools
version: '${project.version}'
main: com.github.kpgtb.ktools.KTools
authors: [ KPG_TB ]
description: An advanced, reloaded version of my tools to Spigot and Paper plugins
website: kpgtb.github.io
softdepend: [PlaceholderAPI, ProtocolLib, GSit]
api-version: 1.13
libraries:
  - com.j256.ormlite:ormlite-jdbc:6.1
  - org.projectlombok:lombok:1.18.30